'use client';

import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    welcome: "Welcome",
    loginTitle: "Welcome Back",
    loginDescription: "Enter your credentials to access your account",
    parentUsername: "Parent Username",
    parentUsernamePlaceholder: "Enter parent's username",
    parentUsernameRequired: "Parent username is required",
    childUsername: "Child Username",
    childUsernamePlaceholder: "Enter child's username",
    childUsernameRequired: "Child username is required",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    passwordRequired: "Password is required",
    login: "Log In",
    myTasks: "My Tasks",
    priority: "Priority",
    completed: "Completed",
    pending: "Pending",
    markComplete: "Mark Complete",
    comments: "Comments",
    addComment: "Add Comment",
    addCommentPlaceholder: "Type your comment here...",
    cancel: "Cancel",
    noTasks: "No tasks available. Great job!",
    loginRequired: "Please log in to view your tasks.",
    errorFetchingTasks: "Error fetching tasks. Please try again.",
    taskCompleted: "Task marked as complete!",
    errorCompletingTask: "Error completing task. Please try again.",
    emptyCommentError: "Please enter a comment before submitting.",
    commentAdded: "Comment added successfully!",
    errorAddingComment: "Error adding comment. Please try again.",
    refresh: "Refresh",
    familyTaskDashboard: "Family Task Dashboard",
    selectChild: "Select a child",
    welcomeMessage: "Hello, {name}! 👋",
    tasksCompleted: "tasks completed",
    of: "of",
    points: "points",
    completeTask: "Complete Task",
    completed: "Completed!",
    taskCompleted: "Great job! Task completed! 🎉",
    errorCompletingTask: "Oops! Couldn't complete the task. Try again!",
    errorFetchingTasks: "Couldn't load tasks. Please refresh!",
    errorFetchingChildren: "Couldn't load children. Please refresh!",
    noTasks: "No tasks for now - Great job! 🌟",
    all: "All Tasks",
    daily: "Daily",
    weekly: "Weekly",
    morning: "Morning",
    evening: "Evening",
    late: "days late",
    refresh: "Refresh Tasks",
    loading: "Loading tasks...",
    addComment: "Add Comment",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    confirmDelete: "Are you sure you want to delete this task?",
    yes: "Yes",
    no: "No",
    loggingIn: "Logging In...",
    loginSuccess: "Login successful!",
    loginError: "Login failed. Please try again.",
    haveAGreatDay: "Have a great day!",
    weeklyTaskOverview: "Weekly Task Overview",
    todaysProgress: "Today's Progress",
    tasksCompleted: "Tasks Completed",
    studyTime: "Study Time",
    exercise: "Exercise",
    upcomingEvents: "Upcoming Events",
    quickActions: "Quick Actions",
    addTask: "Add Task",
    scheduleEvent: "Schedule Event",
    shoppingList: "Shopping List",
    rewards: "Rewards",
    calendar: "Calendar",
    tasks: "Tasks",
    shopping: "Shopping",
    budget: "Budget",
    mealPlanner: "Meal Planner",
    finance: "Finance",
    // Calendar-specific translations
    familyCalendarTitle: "Family Calendar",
    addEvent: "Add Event",
    noEvents: "No events scheduled for this day.",
    newEvent: "New Event",
    eventDetails: "Event Details",
  },
  es: {
    welcome: "Bienvenido",
    haveAGreatDay: "¡Que tengas un buen día!",
    weeklyTaskOverview: "Resumen semanal de tareas",
    todaysProgress: "Progreso de hoy",
    tasksCompleted: "Tareas completadas",
    studyTime: "Tiempo de estudio",
    exercise: "Ejercicio",
    upcomingEvents: "Próximos eventos",
    quickActions: "Acciones rápidas",
    addTask: "Agregar tarea",
    scheduleEvent: "Programar evento",
    shoppingList: "Lista de compras",
    rewards: "Recompensas",
    calendar: "Calendario",
    tasks: "Tareas",
    shopping: "Compras",
    budget: "Presupuesto",
    mealPlanner: "Planificador de comidas",
    finance: "Finanzas",
    familyCalendarTitle: "Calendario Familiar",
    addEvent: "Añadir Evento",
    noEvents: "No hay eventos programados para este día.",
    newEvent: "Nuevo Evento",
    eventDetails: "Detalles del Evento",
  },
  fr: {
    welcome: "Bienvenue",
    haveAGreatDay: "Bonne journée!",
    weeklyTaskOverview: "Aperçu des tâches hebdomadaires",
    todaysProgress: "Progrès d'aujourd'hui",
    tasksCompleted: "Tâches terminées",
    studyTime: "Temps d'étude",
    exercise: "Exercice",
    upcomingEvents: "Événements à venir",
    quickActions: "Actions rapides",
    addTask: "Ajouter une tâche",
    scheduleEvent: "Planifier un événement",
    shoppingList: "Liste de courses",
    rewards: "Récompenses",
    calendar: "Calendrier",
    tasks: "Tâches",
    shopping: "Courses",
    budget: "Budget",
    mealPlanner: "Planificateur de repas",
    finance: "Finances",
    familyCalendarTitle: "Calendrier Familial",
    addEvent: "Ajouter un Événement",
    noEvents: "Aucun événement prévu pour ce jour.",
    newEvent: "Nouvel Événement",
    eventDetails: "Détails de l'Événement",
  },
  de: {
    welcome: "Willkommen",
    haveAGreatDay: "Einen schönen Tag noch!",
    weeklyTaskOverview: "Wöchentliche Aufgabenübersicht",
    todaysProgress: "Heutiger Fortschritt",
    tasksCompleted: "Erledigte Aufgaben",
    studyTime: "Lernzeit",
    exercise: "Übung",
    upcomingEvents: "Kommende Veranstaltungen",
    quickActions: "Schnellaktionen",
    addTask: "Aufgabe hinzufügen",
    scheduleEvent: "Ereignis planen",
    shoppingList: "Einkaufsliste",
    rewards: "Belohnungen",
    calendar: "Kalender",
    tasks: "Aufgaben",
    shopping: "Einkaufen",
    budget: "Budget",
    mealPlanner: "Mahlzeitenplaner",
    finance: "Finanzen",
    familyCalendarTitle: "Familienkalender",
    addEvent: "Ereignis hinzufügen",
    noEvents: "Keine Ereignisse für diesen Tag geplant.",
    newEvent: "Neues Ereignis",
    eventDetails: "Ereignisdetails",
  },
  ru: {
    welcome: "Добро пожаловать",
    haveAGreatDay: "Хорошего дня!",
    weeklyTaskOverview: "Еженедельный обзор задач",
    todaysProgress: "Прогресс на сегодня",
    tasksCompleted: "Завершенные задачи",
    studyTime: "Время на учебу",
    exercise: "Упражнения",
    upcomingEvents: "Предстоящие события",
    quickActions: "Быстрые действия",
    addTask: "Добавить задачу",
    scheduleEvent: "Запланировать событие",
    shoppingList: "Список покупок",
    rewards: "Награды",
    calendar: "Календарь",
    tasks: "Задачи",
    shopping: "Покупки",
    budget: "Бюджет",
    mealPlanner: "Планировщик питания",
    finance: "Финансы",
    familyCalendarTitle: "Семейный календарь",
    addEvent: "Добавить событие",
    noEvents: "На этот день нет запланированных событий.",
    newEvent: "Новое событие",
    eventDetails: "Детали события",
  },
};

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const value = {
    language,
    setLanguage,
    t: translations[language],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
